name: Build image for Reunion
on: [push]
jobs: 
  Build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::009639781021:role/GHA_AWS_OIDC_toy 
          aws-region: us-east-2